services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://wazir:wazirpassword@217.114.10.130:3306/wazir
      - SECRET_KEY=7775c3c9d85f5a9b8c2c28234c2c5d9b8c2c2823
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=2880
      - TELEGRAM_BOT_TOKEN=8181333353:AAFxi9KXFySWWjsr5JTiMXykjaw0JL0gnwo
      - SMS_LOGIN=almaz-91
      - SMS_PASSWORD=sams1488
      - MEDIA_SERVER_URL=https://wazir.kg/media
    volumes:
      - ./media:/app/media
      - ./static:/app/static
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  media_data:
  logs_data: